### PR TITLE
Update dependencies, moving oc erchef to 1.6.4

### PR DESCRIPTION
**Pull request by danielsdeleo**
Removes version restriction on  mochiweb, which is required to get a version compatible with latest erchef. There is something weird going on where ejson seems to want to be locked to mochiweb 1.5.1, but when I update everything I get v2.9.0p1. However this is also the case in oc_erchef which would be failing if that didn't work.

### CODE REVIEW

**Comment by marcparadise** [comment]
:+1: though I'd feel a lot better if we had any means of testing our older migrations :(

**Comment by tylercloke** [comment]
I mean, the current means is making a build and testing the upgrade with some data. If we are concerned about this breaking things, we should do the RightThing(TM) and run that upgrade, painful as it is.

**Comment by marcparadise** [comment]
@tylercloke definitely, I just wish we had coverage within this and moser. It's been on the backlog for quite a while...

**Comment by tylercloke** [comment]
Yeah coverage is wanted for sure.

**Comment by danielsdeleo** [comment]
Okay, what's the next step then? Merge and we test it later (before updating omnibus)?

**Comment by tylercloke** [comment]
@danielsdeleo That sounds good to me. Just lemme know when you are at that point and I can help you out :) :+1:

**Comment by danielsdeleo** [comment]
Will do, thanks!

**Pull request merged**
